sudo: required
services:
 - postgresql
 - mysql
 - elasticsearch
 - rabbitmq
language: python
python:
 - 2.7
 - 3.6

stages:
- lint
- test

addons:
  apt:
    sources:
      - elasticsearch-5.x
    packages:
      - elasticsearch
      - oracle-java8-set-default

cache: pip

before_install: bash -xe travis/before-install.sh
install: pip install -r requirements-dev.txt
script:
- bash -xe travis/unit-tests.sh
- bash -xe travis/test-deploy.sh

jobs:
  include:
  - stage: lint
    python: 3.6
    script:
    - pre-commit run -a
    - radon cc pacifica
  - python: 2.7
    script:
    - pre-commit run -a
    - radon cc pacifica
