services:
 - postgresql
 - mysql
 - elasticsearch
 - rabbitmq
language: python
python:
 - 2.7

addons:
  apt:
    sources:
      - elasticsearch-5.x
    packages:
      - elasticsearch
      - oracle-java8-set-default

matrix:
  include:
    - python: 2.7
    - python: 2.7
      env: RUN_LINTS=true
cache: pip

before_install: bash -xe travis/before-install.sh
install: pip install -r requirements-dev.txt
script: bash -xe travis/test-script.sh
