version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true

environment:
  MYSQL_HOST: localhost
  MYSQL_USER: root
  MYSQL_PASSWORD: Password12!
  PGUSER: postgres
  PGPASSWORD: Password12!
  MYSQL_PATH: C:\Program Files\MySQL\MySQL Server 5.7
  PGSQL_PATH: C:\Program Files\PostgreSQL\9.6
  POSTGRES_ENV_POSTGRES_USER: postgres
  POSTGRES_ENV_POSTGRES_PASSWORD: Password12!
  MYSQL_ENV_MYSQL_USER: root
  MYSQL_ENV_MYSQL_PASSWORD: Password12!
  VOLUME_PATH: C:\ingest
  BROKER_URL: redis://127.0.0.1:6379/0
  BACKEND_URL: redis://127.0.0.1:6379/0

  matrix:
    - PYTHON: C:\Python27-x64
    - PYTHON: C:\Python36-x64

services:
  - mysql
  - postgresql

before_test:
- ps: >
    $env:PATH = "$env:MYSQL_PATH\bin;${env:PGSQL_PATH}\bin;${env:PYTHON}\Scripts;${env:PATH}";
    mysqladmin --host=$env:MYSQL_HOST --user=$env:MYSQL_USER --password=$env:MYSQL_PASSWORD create pacifica_ingest;
    mysqladmin --host=$env:MYSQL_HOST --user=$env:MYSQL_USER --password=$env:MYSQL_PASSWORD create pacifica_uniqueid;
    createdb pacifica_metadata;
    mkdir C:\ingest;
    mkdir C:\archive;
    nuget install redis-64 -excludeversion;
    redis-64\tools\redis-server.exe --service-install;
    redis-64\tools\redis-server.exe --service-start;
    Start-Process $env:PYTHON\python.exe -ArgumentList "$env:PYTHON\scripts\ArchiveInterfaceServer.py --prefix C:\archive" -WorkingDirectory "travis/archivei";
    Start-Process $env:PYTHON\python.exe -ArgumentList "$env:PYTHON\scripts\UniqueIDServer.py" -WorkingDirectory "travis\uniqueid";
    Start-Process $env:PYTHON\python.exe -ArgumentList "$env:PYTHON\scripts\MetadataServer.py" -WorkingDirectory "travis\metadata";
    Start-Process $env:PYTHON\python.exe -ArgumentList "$env:PYTHON\scripts\IngestServer.py" -WorkingDirectory "travis\ingest";
    Start-Process $env:PYTHON\python.exe -ArgumentList "-m celery -A ingest.backend worker --loglevel=info -P eventlet" -WorkingDirectory "travis\ingest";
    Invoke-WebRequest https://github.com/pacifica/pacifica-metadata/archive/master.zip -OutFile pacifica-metadata.zip;
    Expand-Archive pacifica-metadata.zip -DestinationPath C:\pacifica-metadata;
    sleep 10;
    Invoke-WebRequest http://localhost:8121/users;
    pushd C:\pacifica-metadata\pacifica-metadata-master;
    & $env:PYTHON\python.exe -m test_files.loadit;
    popd;
    Start-Process $env:PYTHON\python.exe -ArgumentList "$env:PYTHON\scripts\PolicyServer.py" -WorkingDirectory "travis\policy";
    Invoke-WebRequest http://localhost:8181/status/users/search/dmlb2001/simple -TimeoutSec 1800;

install:
- ps: >
    $env:PATH = "$env:MYSQL_PATH\bin;${env:PGSQL_PATH}\bin;${env:PYTHON}\Scripts;${env:PATH}";
    Invoke-WebRequest -Uri "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.5.zip" -OutFile "elasticsearch.zip";
    Expand-Archive "elasticsearch.zip" -DestinationPath "C:\elasticsearch";
    Start-Process C:\elasticsearch\elasticsearch-5.6.5\bin\elasticsearch;
    & $env:PYTHON\python.exe -m pip install pip setuptools wheel --upgrade;
    & $env:PYTHON\python.exe -m pip install -r requirements-dev.txt;
    & $env:PYTHON\python.exe -m pip install celery[redis] eventlet;

build: off

test_script:
- ps: $env:PATH = "$env:MYSQL_PATH\bin;${env:PGSQL_PATH}\bin;${env:PYTHON}\Scripts;${env:PATH}"
- ps: coverage run --include='uploader_cli/*,CLIUploader.py' CLIUploader.py --config travis/uploader.json --help
- ps: coverage run --include='uploader_cli/*,CLIUploader.py' -a CLIUploader.py --config=travis/uploader.json --help
- ps: $env:UPLOADER_CONFIG = 'travis/uploader.json'
- ps: coverage run --include='uploader_cli/*,CLIUploader.py' -a CLIUploader.py upload --help
- ps: coverage run --include='uploader_cli/*,CLIUploader.py' -a CLIUploader.py configure --help
- ps: yes | coverage run --include='uploader_cli/*,CLIUploader.py' -a CLIUploader.py configure
- ps: coverage run --include='uploader_cli/*,CLIUploader.py' -a -m pytest -v
- ps: coverage report --show-missing --fail-under 100
